### ISSUE TITLE
HTML Layout

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/eac-cpf-taglibrary#7]
All ideas about layout are welcome!

**Comment by MicheleCombs** [comment]
Isn’t it going to be the same as the EAD one, for consistency’s sake?

Michele

**Comment by karinbredenberg** [comment]
Its going to be the same but since the repositry holding them is EAC-CPF....

**Comment by florenceclavaud** [comment]
Karin, 
Where is the XSL that has to be used to get the HTML output ? I suppose it is in the tei_to_html folder ; in this case which of the three XSLTs is the right one ? 

Best,
Florence

**Comment by karinbredenberg** [comment]
Florence,
Sorry for the delay, vacations....
Start of with creating one xml-file for the transformation to run smootly using the tei_to_pdf/CreateOneFile.xsl and save the result.
Now run the tei_to_html/tagLibrary2html_KB_2_git.xsl 
You need to have access to the translationsfile in the tei folder so it gets the correct heading texts.
When you look at the html you need to have the tagLibrary.css in the same folder to get it to look nicer.

Changes in names, removal of the wrong files and a guide will be created when all the work is finished, right now its to much going on to keep that accurate.

will be able to assist you if neeeded during this week. (28/7-1/8)

Best,
Karin

**Comment by karinbredenberg** [comment]
All moved to repo with both TL's.
