### ISSUE TITLE
PDF Layout

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/eac-cpf-taglibrary#8]
All ideas about layout is welcome!

**Comment by MicheleCombs** [comment]
Isn’t it going to be the same as the EAD one, for consistency’s sake?

Michele

**Comment by karinbredenberg** [comment]
Its going to be the same but since the repositry holding them is EAC-CPF....

**Comment by karinbredenberg** [comment]
All moved to new repo with all TL's.
